title: "Jardín Caótico"
description: "Laboratorio de arte, agentes y caos controlado"
url: "https://juandaniel7979.github.io"
baseurl: "/jardincaotico" # raíz del dominio

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Autor principal
author:
  name: "Juan Daniel Vargas Ramírez"
  avatar: "/assets/images/avatar.png"
  bio: "Creando agentes inteligentes, arte generativo y música caótica."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/juandaniel7979"  
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCYjIkXtOF8r3xFModvdVePQ"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jardincaotico/"

# Colecciones (para los sub-blogs)
collections:
  agentes:
    output: true
    permalink: /jardincaotico/agentes/:path/
  arte:
    output: true
    permalink: /jardincaotico/arte/:path/
  musica:
    output: true
    permalink: /jardincaotico/musica/:path/

# Defaults por colección
defaults:
  - scope:
      path: ""
      type: "agentes"
    values:
      layout: single
      author: Juan D Vargas R
      category: agentes
      permalink: /jardincaotico/agentes/:title/
  - scope:
      path: ""
      type: "arte"
    values:
      layout: single
      category: arte
      permalink: /jardincaotico/arte/:title/
  - scope:
      path: ""
      type: "musica"
    values:
      layout: single
      category: musica
      permalink: /jardincaotico/musica/:title/
